### ISSUE TITLE
Alignement Typography

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#924]
**To-do's:**
- [x] Design page-layout for merge (Storybook)
- [x] Merge all Typo pages together 
- [x] Add Spacing examples 

Question: How do we integrate Figma?
